### ISSUE TITLE
[Feature] Binder Notebooks

### ISSUE THREAD

**Issue by costrouc** [plures/xnd#17]
Wanting to get feedback and begin adding a [jupyterhub binder](https://binderhub.readthedocs.io/en/latest/) for the xnd project. From reading the documentation xnd seems to quite fully featured and it would be nice to allow users to quickly experiment with the python interface. I think on the biggest barriers that users at the pycon sprint has was getting started with the library. 

If you believe this is worth creating I will setup a binder notebook for xnd.

**Comment by saulshanabrook** [comment]
You mean for https://mybinder.org/ ?

**Comment by costrouc** [comment]
Yes. I liked to the documentation but I believe that the project is run [under jupyterhub](https://github.com/jupyterhub/binderhub). It would allow uses to quickly experiment with features and get used to the interface. 

Here is an example of a conda demo. https://github.com/binder-examples/conda

Not sure of the folder structure you would like but I imagine a structure like.

```
notebooks/
      gettingstarted.ipynb
      types.ipynb
      alignment.ipynb

doc/
      notebooks/
           gettingstarted.ipynb
           types.ipynb
           alignment.ipynb
```

**Comment by skrah** [comment]
Before you put a lot of work into this:  I'm not quite sure yet if I want that feature in. It means an additional item to maintain.

I think users can copy and paste the doc examples from readthedocs.org. I've deliberately added the prompt-toggling feature to copy/paste easier.

**Comment by costrouc** [comment]
I agree that it is another thing to maintain and I have found it tedious in some of my projects to maintain. 

To help myself and others with learning I have created a [collection of binder notebooks](https://github.com/costrouc/xnd-notebooks). I do believe that there should be some option for people to jump into the project and explore its features quickly.
