### ISSUE TITLE
conda build uses incorrect Python version

### ISSUE THREAD

**Issue by pearu** [plures/xnd#23]
Consider for example
  https://travis-ci.org/plures/xnd/jobs/402274123
According to the build logs, xnd is build and installed using python3.7 but the build filename contains Python 3.6 version: `xnd-0.2.0dev3-py36_118_g1c2bdb3.tar.bz2` , for instance.
As a result, `conda install xnd` will result broken xnd installation.

**Comment by xmnlab** [comment]
I can investigate this issue

**Comment by saulshanabrook** [comment]
Fixed by #24.
