### ISSUE TITLE
Add more NumPy API functions/attributes to xnd_gumath class

### ISSUE THREAD

**Issue by xmnlab** [plures/xnd#28]

**Comment by andersy005** [comment]
@xmnlab, 

Is this issue referring to the `xnd_gumath` class from https://github.com/Quansight/xnd-notebooks/blob/master/utils/math_utils.ipynb ? If so, wouldn't it be better to transfer the xnd-notebooks repo from Quansight to plures organization and then transfer this issue there?

**Comment by xmnlab** [comment]
this issue is being moved to xnd-all repo project.
